<!DOCTYPE html>
<html lang="en">
<head>
<base href="www.chilenetwork.cl/desarrollo-web">
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CNetwork - Desarrollo Web</title>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style type="text/css">
  
body {
  padding-top: 50px;
  padding-bottom: 20px;
}
h1 {
    color: #719e40;
    letter-spacing: -3px;
    font-family: 'Lato', sans-serif;
    font-size: 25px;
    font-weight: 200;
    margin-bottom: 0;
}

</style>
</head>
<body>
 
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="https://www.chilenetwork.cl">ChileNetwork</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <!--<li class="active"><a href="desarrollo-web">Desarrollo Web</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>-->
          </ul>
        </div><!--/.nav-collapse -->
       
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container" style="text-align: justify;">
       Blog - A Broader View
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12">
          <h2>EL Proyecto</h2>
          <p> ABV quien esta encargado de entregar un servicio a personas que tengan la necesidad de voluntariar en colaboracion a la sociedad.(each Slim app route MUST return a PSR 7 Response object)</p>
           <h2>FronEnd</h2>
           Donde vive el Public Site de ABV. Menus y descripcion de los deferentes programas que tiene nuestra organizacion para ofrecer a los entusiastas voluntarios.
          <p><a class="btn btn-default" href="desarrollo-web" role="button">View details &raquo;</a></p>
          <h2>https://abv.chilenetwork.cl/</h2>
        </div>
       
      </div>

      <hr>

      <footer>
        <p>&copy; 2017 ChileNetwork, Chile</p>
      </footer>
    </div> <!-- /container -->

   
</body>
</html>





