<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>ChileNetwork</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <style type="text/css">body {padding-top:50px;padding-bottom:20px;}h1{color:#719e40;letter-spacing:-3px;font-family:'Lato',sans-serif;font-size:25px;font-weight:200;margin-bottom: 0;}</style>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="https://www.chilenetwork.cl">ChileNetwork</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
            </ul>
            </div>
        </div>
        </nav>
        <div class="jumbotron">
            <div class="container">
                <div class="row">
                    <h2 style="text-align: center;">API -  <span style="font-family: Arial;">Respuesta en formato Json en mili segundos!</span></h2>
                </div>

            </div>
            <table class="table"> 
                <thead> 
                    <tr> 
                        <th>#</th> 
                        <th>Api Service</th> 
                       <th>Descripcion</th> 
                        <th>Uso</th> 
                    </tr> 
                </thead> 
                <tbody> 
                <tr class="active"> 
                    <th scope="row">1</th> 
                    <td>http://www.mindicador.cl/api/</td> 
                    <td>Devuelve indicadores economicos. Informacion segun el tipo y rango de fecha</td> 
                    <td>/api/{codigo}/{fecha}. Ejemplo: /api/dolar/05-01-2017</td> 
                </tr> 
              
                <tr class="success"> 
                    <th scope="row">3</th> 
                    <td>Column content</td> 
                    <td>Column content</td> 
                    <td>Column content</td> 
                </tr> 
                </tbody> </table>
            <div class="alert alert-danger" role="alert">
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                  <span class="sr-only">Error:</span>
                  Enter a valid email address
                </div>
        </div>
        <footer>
            <p style="text-align: center;">&copy; 2017 ChileNetwork, Chile</p>
        </footer>

</body>
</html>
