<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>ChileNetwork</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 50px;
                font-weight: 200;
                margin-bottom: 0;
            }
            #wrapper {
      margin-right: auto;
      margin-left: auto;
      width: 960px;
    }
    #header {
      margin-right: 10px;
      margin-left: 10px;
      width: 940px;
    }
    #navigation {
      padding-bottom: 25px;
      margin-top: 26px;
      margin-left: -10px;
      padding-right: 10px;
      padding-left: 10px;
      width: 940px;
    }
    #navigation ul li {
      display: inline-block;
    }
    #content {
      margin-top: 58px;
      margin-right: 10px;
      float: right;
      width: 698px;
    }
    #sidebar {
      border-right-color: #e8e8e8;
      border-right-style: solid;
      border-right-width: 2px;
      margin-top: 58px;
      padding-right: 10px;
      margin-right: 10px;
      margin-left: 10px;
      float: left;
      width: 220px;
    }
    #footer {
      float: left;
      margin-top: 20px;
      margin-right: 10px;
      margin-left: 10px;
      clear: both;
      width: 940px;
    }
        </style>
    </head>
    <body>
        <div>
            <h1>Desarrollo Aplicaciones Web</h1>
            <h3>Powered by Slim</h3>
            <p>a microframework for PHP</p>
       

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <!--<p>Try <a href="http://www.slimframework.com">SlimFramework</a>-->
        <?php endif; ?>
         </div>

<div id="wrapper">
<!-- the header and navigation -->
<div id="header">
<div id="navigation">
<ul>
<li><a href="#">navigation1</a></li>
<li><a href="#">navigation2</a></li>
</ul>
</div>
</div>
<!-- the sidebar -->
<div id="sidebar">
<p>here is the sidebar</p>
</div>
<!-- the content -->
<div id="content">
<p>here is the content</p>
</div>
<!-- the footer -->
<div id="footer">
<p>Here is the footer</p>
</div>
</div>
    </body>
</html>
