<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ChileNetwork</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Oswald|Amatic+SC" rel="stylesheet">
<style type="text/css">
body {padding-top:50px;padding-bottom: 20px;}
h1 {color: #719e40;letter-spacing:-3px;font-family:'Lato',sans-serif;font-size:25px;font-weight:200;margin-bottom:0;}</style>
</head>
<body>
 
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="https://www.chilenetwork.cl">ChileNetwork</a>
        </div>
         <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          </ul>
        </div>
      </div>
    </nav>
   
    <div class="jumbotron">
      <div class="container">
      <!-- <span style="font-family: 'Amatic SC', cursive;font-size: 45"></span> -->
        <div class="row">
          <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading" >Desarrollo Web</div>
              <div class="panel-body">Desarrollo de aplicaciones Web utilizando los estandares requeridos para la industria.</div>
            </div>

          </div>

          <div class="col-md-4">
           <div class="panel panel-default">
              <div class="panel-heading" style="font-family:'Oswald';">FrameWorks</div>
              <div class="panel-body">Generadores de sistemas web base estandar. Toda la infraestructura para gestionar protocolos http y https. frameworks using PSR-7 style middlewares. tuupola/slim-basic-auth</div>
            </div>
                 
          </div>


          <div class="col-md-4"> 
          <div class="panel panel-default">
              <div class="panel-heading" style="font-family:'Oswald';">Api</div>
              <div class="panel-body">
                <p> JSon Responses  <a class="btn" href="api/mindicador" target="_blank">Mini Indicador Economico /{codigo} &raquo;</a> </p>
               
               

            
              </div>
            </div>

          </div>
          
        </div>
      
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Business Logic</h2>
          <p>Propiedad intelectual para el respaldo de tus datos</p>
          <p><a class="btn btn-default" href="desarrollo-web" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Estandares</h2>
          <p>La construccion y desarrollo de aplicaciones para la web ha alcanzado tecnicas en su arquitectura optimizando asi la implementacion de rutas y dependencias de terceras partes. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Proyectos</h2>
          <p>Nuestro equipo desarrolla utilizando Slim. Un microframework para PHP el cual es codigo base para construir aplicaciones estandares y robustas. Construccion de componentes personalizados pudiendo se integrados a su sitema o sus analogos como Laravel o Symfony</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2017 ChileNetwork, Chile</p>
      </footer>
    </div> <!-- /container -->

    <?php if (isset($name)) : ?>
    <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
    <?php else: ?>
    <!--<p>Try <a href="http://www.slimframework.com">SlimFramework</a>-->
    <?php endif; ?>

<div> <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Entrar</button>
          </form>
        </div><!--/.navbar-collapse --></div>   
</body>
</html>





